# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-08 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_fileNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_Agenda', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('descript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer_question_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cause_file_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cause_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cause_txt', models.CharField(max_length=255, verbose_name='نام دلیل ')),
                ('Cause_descript', models.TextField(verbose_name='شرح مختصری ار دلایل مورد نظر')),
            ],
            options={
                'verbose_name': 'مدیریت  دلیل رفتاری ',
                'verbose_name_plural': 'مدیریت دلایل رفتاری',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('file_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=250)),
                ('date_birthday', models.DateField()),
                ('grade_Educations', models.IntegerField()),
                ('disability', models.BooleanField(default=False)),
                ('mental_problems', models.TextField(blank=True, null=True)),
                ('Physical_problems', models.TextField(blank=True, null=True)),
                ('Date_create', models.DateField()),
                ('Parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Children_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Behavior_name', models.CharField(max_length=255)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_FileNumber_Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Descript_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discrip', models.TextField(null=True)),
                ('date_time', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('Status_before_bahavior', models.TextField()),
                ('Result_behavior', models.TextField()),
                ('Comments', models.TextField(null=True)),
                ('Behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='general_noting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField()),
                ('consultant', models.ForeignKey(db_column='consultant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Helper_file_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Helper', models.ForeignKey(db_column='helper', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs_Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_en', models.CharField(max_length=250)),
                ('txt_fr', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='notting_fileNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField()),
                ('consultant', models.ForeignKey(db_column='consultant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birth_date', models.DateField()),
                ('matrial_status', models.CharField(max_length=250)),
                ('jobs', models.CharField(max_length=250)),
                ('education_degree', models.CharField(max_length=250)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_degree', models.CharField(max_length=250)),
                ('profile_image_psy', models.ImageField(upload_to='pic_profile_psy_folder/')),
                ('Specialist_in_Field_work', models.TextField()),
                ('biography', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('during_session', models.DurationField()),
                ('Code_organization', models.CharField(max_length=50)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='psychology', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('descript', models.TextField(null=True)),
                ('result', models.TextField()),
                ('Date_Time', models.DateTimeField()),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='punishment_recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام تنبیه ')),
                ('descript', models.TextField(verbose_name='شرح مختصری ار تنبیه مورد نظر')),
            ],
            options={
                'verbose_name': 'مدیریت  تنبیه پیشنهاد شده به کاربر ',
                'verbose_name_plural': 'مدیریت تنبیه های  پیشنهاد شده به کاربر ',
            },
        ),
        migrations.CreateModel(
            name='record_behavior_Weekly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('Times', models.IntegerField()),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='request_consultant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_request', models.DateField()),
                ('activ_req', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (0, 'Reject')], default=1)),
                ('date_active', models.DateField(null=True)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
                ('user_psy', models.ForeignKey(db_column='user_psy', on_delete=django.db.models.deletion.CASCADE, related_name='user_psy', to=settings.AUTH_USER_MODEL)),
                ('user_request', models.ForeignKey(db_column='user_request', on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Reward_txt', models.CharField(max_length=255, verbose_name='نام پاداش ')),
                ('Reward_descript', models.TextField(verbose_name='شرح مختصری ار پاداش مورد نظر')),
            ],
            options={
                'verbose_name': 'مدیریت  پاداش رفتاری پیشنهاد شده به کاربر ',
                'verbose_name_plural': 'مدیریت پاداش های رفتاری پیشنهاد شده به کاربر ',
            },
        ),
        migrations.CreateModel(
            name='Rewards_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Reward_txt', models.CharField(max_length=255, verbose_name='نام پاداش ')),
                ('Reward_descript', models.TextField(null=True, verbose_name='شرح مختصری ار پاداش مورد نظر')),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
            ],
        ),
        migrations.CreateModel(
            name='Rules_Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rule_txt', models.CharField(max_length=255)),
                ('Rule_descript', models.TextField()),
                ('Reward', models.ForeignKey(db_column='Reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rewards_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Time_Cost_filenumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('Cost', models.IntegerField()),
                ('comment', models.TextField()),
                ('request', models.ForeignKey(db_column='request', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.request_consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Situation_defficult_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField(null=True)),
                ('grade', models.IntegerField()),
                ('Date_Time', models.DateTimeField()),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality_Education_psy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_en', models.CharField(max_length=100)),
                ('txt_fr', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Star_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField()),
                ('reward_rule', models.ForeignKey(db_column='reward_rule', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rules_Reward')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steps_exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255, verbose_name='نام مرحله تمرین ')),
                ('exercise_text', models.TextField(verbose_name='متن مرحله آمورشی ')),
            ],
            options={
                'verbose_name': 'مدیریت  تمرین آموزش ',
                'verbose_name_plural': 'مدیریت تمرینات آمورشی',
            },
        ),
        migrations.CreateModel(
            name='Steps_training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_Steps', models.CharField(max_length=255, verbose_name='نام مرحله آمورشی ')),
                ('text_Training_steps', models.TextField(verbose_name='متن آموزشی')),
                ('example_Training_steps', models.TextField(null=True, verbose_name='مثال های مرحله آموزشی')),
                ('question_common_Training_steps', models.TextField(null=True, verbose_name='پرسش های متداول مرحله آموزشی ')),
            ],
            options={
                'verbose_name': 'مدیریت مرحله آموزشی ',
                'verbose_name_plural': 'مدیریت مراحل آمورشی',
            },
        ),
        migrations.CreateModel(
            name='Surprice_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField()),
                ('Reward', models.ForeignKey(db_column='bahavior_reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rewards_behavior')),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='type_of_Rewrard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=255, verbose_name='نوع پاداش ')),
                ('descript', models.TextField(null=True, verbose_name='شرح مختصری ار نوع پاداش مورد نظر')),
            ],
            options={
                'verbose_name': 'مدیریت  نوع پاداش رفتاری ',
                'verbose_name_plural': 'مدیریت انواع پاداش  رفتاری ',
            },
        ),
        migrations.AddField(
            model_name='steps_exercise',
            name='steps',
            field=models.ForeignKey(db_column='steps', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_training', verbose_name='مربوط به کدام مرحله آموزش '),
        ),
        migrations.AddField(
            model_name='rewards_behavior',
            name='type_of_Reward',
            field=models.ForeignKey(db_column='type_reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.type_of_Rewrard'),
        ),
        migrations.AddField(
            model_name='rewards_behavior',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewards',
            name='type_of_Reward',
            field=models.ForeignKey(db_column='type_reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.type_of_Rewrard'),
        ),
        migrations.AddField(
            model_name='comments_filenumber_training',
            name='Steps',
            field=models.ForeignKey(db_column='Steps', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_training'),
        ),
        migrations.AddField(
            model_name='comments_filenumber_training',
            name='file_number',
            field=models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children'),
        ),
        migrations.AddField(
            model_name='cause_file_number',
            name='Cause',
            field=models.ForeignKey(db_column='Cause', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Cause_list'),
        ),
        migrations.AddField(
            model_name='cause_file_number',
            name='behavior',
            field=models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior'),
        ),
        migrations.AddField(
            model_name='cause_file_number',
            name='user',
            field=models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer_question_request',
            name='request',
            field=models.ForeignKey(db_column='request', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.request_consultant'),
        ),
        migrations.AddField(
            model_name='answer_exercise',
            name='Exercise',
            field=models.ForeignKey(db_column='Steps_Exercise', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_exercise'),
        ),
        migrations.AddField(
            model_name='answer_exercise',
            name='file_number',
            field=models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children'),
        ),
        migrations.AddField(
            model_name='agenda_filenumber',
            name='file_number',
            field=models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children'),
        ),
        migrations.AddField(
            model_name='agenda_filenumber',
            name='user_psy',
            field=models.ForeignKey(db_column='user_psy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
