# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('file_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_birthday', models.DateField()),
                ('grade_Educations', models.CharField(max_length=255)),
                ('disability', models.BooleanField(default=False)),
                ('mental_problems', models.TextField(blank=True, null=True)),
                ('Physical_problems', models.TextField(blank=True, null=True)),
                ('Parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs_Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_en', models.CharField(max_length=250)),
                ('txt_fr', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birth_date', models.DateField()),
                ('matrial_status', models.CharField(max_length=250)),
                ('jobs', models.CharField(max_length=250)),
                ('education_degree', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Psy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_degree', models.IntegerField()),
                ('profile_image_psy', models.ImageField(upload_to='pic_profile_psy_folder/')),
                ('Specialist_in_Field_work', models.TextField()),
                ('biography', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('during_session', models.DurationField()),
                ('Code_organzation', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='psychology', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality_Education_psy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_en', models.CharField(max_length=100)),
                ('txt_fr', models.CharField(max_length=250)),
            ],
        ),
    ]
