# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
