# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0002_auto_20190226_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('file_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_birthday', models.DateField()),
                ('grade_Educations', models.CharField(max_length=255)),
                ('disability', models.BooleanField(default=False)),
                ('mental_problems', models.TextField(blank=True, null=True)),
                ('Physical_problems', models.TextField(blank=True, null=True)),
                ('Parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
