# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0003_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_psy',
            old_name='Code_organzation',
            new_name='Code_organization',
        ),
    ]
