# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-09 10:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0003_auto_20190609_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='file_number',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{8}$')]),
        ),
    ]
