# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0004_auto_20190609_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descript_behavior',
            name='date_time',
            field=models.DateField(),
        ),
    ]
