# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0005_auto_20190618_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_behavior_weekly',
            name='date',
            field=models.DateField(),
        ),
    ]
