# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0006_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='id',
            new_name='file_number',
        ),
        migrations.AddField(
            model_name='children',
            name='family',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='children',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
