# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0006_auto_20190620_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules_reward',
            name='Reward',
        ),
        migrations.RemoveField(
            model_name='star_table',
            name='reward_rule',
        ),
        migrations.AddField(
            model_name='rules_reward',
            name='behavior',
            field=models.ForeignKey(db_column='behavior', default='1', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star_table',
            name='reward',
            field=models.ForeignKey(db_column='reward', default='1', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rewards_behavior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star_table',
            name='rule',
            field=models.ForeignKey(db_column='rule', default='1', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rules_Reward'),
            preserve_default=False,
        ),
    ]
