# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0007_auto_20190227_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='Date_create',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
