# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0007_auto_20190622_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_table',
            name='behavior',
            field=models.ForeignKey(db_column='behavior', default='1', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior'),
            preserve_default=False,
        ),
    ]
