# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0008_star_table_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_table',
            name='times',
            field=models.IntegerField(db_column='times', default=0),
        ),
    ]
