# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0008_children_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps_training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_Steps', models.CharField(max_length=255)),
                ('text_Training_steps', models.TextField()),
                ('example_Training_steps', models.TextField()),
                ('question_common_Training_steps', models.TextField()),
            ],
        ),
    ]
