# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0009_steps_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps_exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_text', models.TextField()),
                ('steps', models.ForeignKey(db_column='steps', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_training')),
            ],
        ),
    ]
