# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0010_auto_20190622_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishment_behavior',
            name='Date_Time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='surprice_table',
            name='Date_Time',
            field=models.DateField(),
        ),
    ]
