# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0010_steps_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_exercise',
            name='exercise_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='steps_training',
            name='example_Training_steps',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='steps_training',
            name='question_common_Training_steps',
            field=models.TextField(null=True),
        ),
    ]
