# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0011_auto_20190302_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments_FileNumber_Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Comments', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='steps_exercise',
            options={'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u062a\u0645\u0631\u06cc\u0646 \u0622\u0645\u0648\u0632\u0634 ', 'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u062a\u0645\u0631\u06cc\u0646\u0627\u062a \u0622\u0645\u0648\u0631\u0634\u06cc'},
        ),
        migrations.AlterModelOptions(
            name='steps_training',
            options={'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u0645\u0631\u062d\u0644\u0647 \u0622\u0645\u0648\u0632\u0634\u06cc ', 'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u0645\u0631\u0627\u062d\u0644 \u0622\u0645\u0648\u0631\u0634\u06cc'},
        ),
        migrations.AlterField(
            model_name='steps_exercise',
            name='exercise_name',
            field=models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u0645\u0631\u062d\u0644\u0647 \u062a\u0645\u0631\u06cc\u0646 '),
        ),
        migrations.AlterField(
            model_name='steps_exercise',
            name='exercise_text',
            field=models.TextField(verbose_name='\u0645\u062a\u0646 \u0645\u0631\u062d\u0644\u0647 \u0622\u0645\u0648\u0631\u0634\u06cc '),
        ),
        migrations.AlterField(
            model_name='steps_exercise',
            name='steps',
            field=models.ForeignKey(db_column='steps', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_training', verbose_name='\u0645\u0631\u0628\u0648\u0637 \u0628\u0647 \u06a9\u062f\u0627\u0645 \u0645\u0631\u062d\u0644\u0647 \u0622\u0645\u0648\u0632\u0634 '),
        ),
        migrations.AlterField(
            model_name='steps_training',
            name='example_Training_steps',
            field=models.TextField(null=True, verbose_name='\u0645\u062b\u0627\u0644 \u0647\u0627\u06cc \u0645\u0631\u062d\u0644\u0647 \u0622\u0645\u0648\u0632\u0634\u06cc'),
        ),
        migrations.AlterField(
            model_name='steps_training',
            name='name_Steps',
            field=models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u0645\u0631\u062d\u0644\u0647 \u0622\u0645\u0648\u0631\u0634\u06cc '),
        ),
        migrations.AlterField(
            model_name='steps_training',
            name='question_common_Training_steps',
            field=models.TextField(null=True, verbose_name='\u067e\u0631\u0633\u0634 \u0647\u0627\u06cc \u0645\u062a\u062f\u0627\u0648\u0644 \u0645\u0631\u062d\u0644\u0647 \u0622\u0645\u0648\u0632\u0634\u06cc '),
        ),
        migrations.AlterField(
            model_name='steps_training',
            name='text_Training_steps',
            field=models.TextField(verbose_name='\u0645\u062a\u0646 \u0622\u0645\u0648\u0632\u0634\u06cc'),
        ),
        migrations.AddField(
            model_name='comments_filenumber_training',
            name='Steps',
            field=models.ForeignKey(db_column='Steps_training', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_training'),
        ),
        migrations.AddField(
            model_name='comments_filenumber_training',
            name='file_number',
            field=models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children'),
        ),
        migrations.AddField(
            model_name='answer_exercise',
            name='Exercise',
            field=models.ForeignKey(db_column='Steps_Exercise', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_exercise'),
        ),
        migrations.AddField(
            model_name='answer_exercise',
            name='file_number',
            field=models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children'),
        ),
    ]
