# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0011_auto_20190623_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation_defficult_behavior',
            name='Date_Time',
            field=models.DateField(),
        ),
    ]
