# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0012_auto_20190302_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_filenumber_training',
            name='Steps',
            field=models.ForeignKey(db_column='Steps', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Steps_training'),
        ),
    ]
