# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0012_auto_20190623_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_time_cost_filenumber',
            name='duration',
        ),
        migrations.AddField(
            model_name='set_time_cost_filenumber',
            name='duration_ee',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
