# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-26 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0013_auto_20190626_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set_time_cost_filenumber',
            old_name='duration_ee',
            new_name='duration',
        ),
    ]
