# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0013_auto_20190302_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Behavior_name', models.CharField(max_length=255)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Descript_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discrip', models.TextField(null=True)),
                ('date_time', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('Status_before_bahavior', models.TextField()),
                ('Result_behavior', models.TextField()),
                ('Comments', models.TextField(null=True)),
                ('Behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
            ],
        ),
        migrations.CreateModel(
            name='Week_record_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('Times', models.IntegerField()),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
            ],
        ),
    ]
