# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0014_children_behavior_descript_behavior_week_record_behavior'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Week_record_behavior',
            new_name='record_behavior_Weekly',
        ),
    ]
