# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0015_auto_20190303_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='descript_behavior',
            name='user',
            field=models.ForeignKey(db_column='User', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record_behavior_weekly',
            name='user',
            field=models.ForeignKey(db_column='User', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
