# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0016_auto_20190305_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descript_behavior',
            name='user',
        ),
        migrations.RemoveField(
            model_name='record_behavior_weekly',
            name='user',
        ),
    ]
