# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0018_auto_20190305_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause_file_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cause_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cause_txt', models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u062f\u0644\u06cc\u0644 ')),
                ('Cause_descript', models.TextField(verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u062f\u0644\u0627\u06cc\u0644 \u0645\u0648\u0631\u062f \u0646\u0638\u0631')),
            ],
            options={
                'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u062f\u0644\u06cc\u0644 \u0631\u0641\u062a\u0627\u0631\u06cc ',
                'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u062f\u0644\u0627\u06cc\u0644 \u0622\u0645\u0648\u0631\u0634\u06cc',
            },
        ),
        migrations.AddField(
            model_name='cause_file_number',
            name='Cause',
            field=models.ForeignKey(db_column='Cause', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Cause_list'),
        ),
        migrations.AddField(
            model_name='cause_file_number',
            name='behavior',
            field=models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior'),
        ),
        migrations.AddField(
            model_name='cause_file_number',
            name='user',
            field=models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
