# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0019_auto_20190305_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Reward_txt', models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u062f\u0644\u06cc\u0644 ')),
                ('Reward_descript', models.TextField(verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u062f\u0644\u0627\u06cc\u0644 \u0645\u0648\u0631\u062f \u0646\u0638\u0631')),
            ],
            options={
                'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u067e\u0627\u062f\u0627\u0634 \u0631\u0641\u062a\u0627\u0631\u06cc ',
                'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u067e\u0627\u062f\u0627\u0634 \u0647\u0627\u06cc \u0631\u0641\u062a\u0627\u0631\u06cc ',
            },
        ),
        migrations.CreateModel(
            name='type_of_Rewrard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=255, verbose_name='\u0646\u0648\u0639 \u067e\u0627\u062f\u0627\u0634 ')),
                ('descript', models.TextField(null=True, verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u0646\u0648\u0639 \u067e\u0627\u062f\u0627\u0634 \u0645\u0648\u0631\u062f \u0646\u0638\u0631')),
            ],
            options={
                'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u0646\u0648\u0639 \u067e\u0627\u062f\u0627\u0634 \u0631\u0641\u062a\u0627\u0631\u06cc ',
                'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u0627\u0646\u0648\u0627\u0639 \u067e\u0627\u062f\u0627\u0634  \u0631\u0641\u062a\u0627\u0631\u06cc ',
            },
        ),
        migrations.AlterModelOptions(
            name='cause_list',
            options={'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u062f\u0644\u06cc\u0644 \u0631\u0641\u062a\u0627\u0631\u06cc ', 'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u062f\u0644\u0627\u06cc\u0644 \u0631\u0641\u062a\u0627\u0631\u06cc'},
        ),
        migrations.AddField(
            model_name='rewards',
            name='type_of_Rewrard',
            field=models.ForeignKey(db_column='type_reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.type_of_Rewrard'),
        ),
    ]
