# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0020_auto_20190305_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Reward_txt', models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u067e\u0627\u062f\u0627\u0634 ')),
                ('Reward_descript', models.TextField(null=True, verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u067e\u0627\u062f\u0627\u0634 \u0645\u0648\u0631\u062f \u0646\u0638\u0631')),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('type_of_Reward', models.ForeignKey(db_column='type_reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.type_of_Rewrard')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rules_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rule_txt', models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u067e\u0627\u062f\u0627\u0634 ')),
                ('Rule_descript', models.TextField(null=True, verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u067e\u0627\u062f\u0627\u0634 \u0645\u0648\u0631\u062f \u0646\u0638\u0631')),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u067e\u0627\u062f\u0627\u0634 \u0631\u0641\u062a\u0627\u0631\u06cc \u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u0634\u062f\u0647 \u0628\u0647 \u06a9\u0627\u0631\u0628\u0631 ', 'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u067e\u0627\u062f\u0627\u0634 \u0647\u0627\u06cc \u0631\u0641\u062a\u0627\u0631\u06cc \u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u0634\u062f\u0647 \u0628\u0647 \u06a9\u0627\u0631\u0628\u0631 '},
        ),
        migrations.RenameField(
            model_name='rewards',
            old_name='type_of_Rewrard',
            new_name='type_of_Reward',
        ),
        migrations.AlterField(
            model_name='rewards',
            name='Reward_descript',
            field=models.TextField(verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u067e\u0627\u062f\u0627\u0634 \u0645\u0648\u0631\u062f \u0646\u0638\u0631'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='Reward_txt',
            field=models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u067e\u0627\u062f\u0627\u0634 '),
        ),
    ]
