# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0021_auto_20190305_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules_behavior',
            name='behavior',
        ),
        migrations.AddField(
            model_name='rules_behavior',
            name='Reward',
            field=models.ForeignKey(db_column='Reward', default=1, on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rewards_behavior'),
            preserve_default=False,
        ),
    ]
