# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0022_auto_20190305_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules_Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rule_txt', models.CharField(max_length=255, null=True)),
                ('Rule_descript', models.TextField(null=True)),
                ('Reward', models.ForeignKey(db_column='Reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rewards_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rules_behavior',
            name='Reward',
        ),
        migrations.RemoveField(
            model_name='rules_behavior',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rules_behavior',
        ),
    ]
