# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0023_auto_20190305_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Surprice_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField()),
                ('Rewards_behavior', models.ForeignKey(db_column='bahavior_reward', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rewards_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rules_reward',
            name='Rule_descript',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rules_reward',
            name='Rule_txt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star_table',
            name='reward_rule',
            field=models.ForeignKey(db_column='reward_rule', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Rules_Reward'),
        ),
        migrations.AddField(
            model_name='star_table',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
