# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0024_auto_20190306_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surprice_table',
            old_name='Rewards_behavior',
            new_name='Reward',
        ),
    ]
