# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0025_auto_20190306_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='surprice_table',
            name='behavior',
            field=models.ForeignKey(db_column='behavior', default=1, on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior'),
            preserve_default=False,
        ),
    ]
