# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0026_surprice_table_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='punishment_recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('punish_txt', models.CharField(max_length=255, verbose_name='\u0646\u0627\u0645 \u062a\u0646\u0628\u06cc\u0647 ')),
                ('punish_descript', models.TextField(verbose_name='\u0634\u0631\u062d \u0645\u062e\u062a\u0635\u0631\u06cc \u0627\u0631 \u062a\u0646\u0628\u06cc\u0647 \u0645\u0648\u0631\u062f \u0646\u0638\u0631')),
            ],
            options={
                'verbose_name': '\u0645\u062f\u06cc\u0631\u06cc\u062a  \u062a\u0646\u0628\u06cc\u0647 \u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u0634\u062f\u0647 \u0628\u0647 \u06a9\u0627\u0631\u0628\u0631 ',
                'verbose_name_plural': '\u0645\u062f\u06cc\u0631\u06cc\u062a \u062a\u0646\u0628\u06cc\u0647 \u0647\u0627\u06cc  \u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u0634\u062f\u0647 \u0628\u0647 \u06a9\u0627\u0631\u0628\u0631 ',
            },
        ),
    ]
