# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0027_punishment_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('descript', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situation_defficult_behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField(null=True)),
                ('grade', models.IntegerField()),
                ('behavior', models.ForeignKey(db_column='behavior', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children_behavior')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='punishment_recommend',
            old_name='punish_descript',
            new_name='descript',
        ),
        migrations.RenameField(
            model_name='punishment_recommend',
            old_name='punish_txt',
            new_name='name',
        ),
    ]
