# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0029_auto_20190307_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_consultant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_request', models.DateField()),
                ('activ_req', models.BooleanField(default=False)),
                ('date_active', models.DateField(null=True)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
                ('user_psy', models.ForeignKey(db_column='user_psy', on_delete=django.db.models.deletion.CASCADE, related_name='user_psy', to=settings.AUTH_USER_MODEL)),
                ('user_request', models.ForeignKey(db_column='user_request', on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
