# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0030_request_consultant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_fileNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_Agenda', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('descript', models.TextField()),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
                ('user_psy', models.ForeignKey(db_column='user_psy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
