# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0031_agenda_filenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_consultant',
            name='activ_req',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Reject'), (2, 'accept')], default=0),
        ),
    ]
