# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0033_auto_20190310_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Time_Cost_filenumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('Cost', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterField(
            model_name='request_consultant',
            name='activ_req',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (0, 'Reject')], default=1),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='set_time_cost_filenumber',
            name='request',
            field=models.ForeignKey(db_column='request', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.request_consultant'),
        ),
    ]
