# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farzand_Parvari_app', '0034_auto_20190313_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_question_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('request', models.ForeignKey(db_column='request', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.request_consultant')),
            ],
        ),
    ]
