# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0035_answer_question_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_noting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField()),
                ('consultant', models.ForeignKey(db_column='consultant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notting_fileNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField()),
                ('consultant', models.ForeignKey(db_column='consultant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
            ],
        ),
        migrations.AlterField(
            model_name='answer_question_request',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
