# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farzand_Parvari_app', '0036_auto_20190316_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper_file_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Helper', models.ForeignKey(db_column='helper', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_number', models.ForeignKey(db_column='file_number', on_delete=django.db.models.deletion.CASCADE, to='Farzand_Parvari_app.Children')),
            ],
        ),
    ]
